version: '2.2'


# 备份数据目录:　tar -zcvf all_docker_data.tar.gz airprint alist clouddrive iventoy lucky next-terminal openvpn-as twonav postgresql wordpress all_docker-compose.yml

networks:
  docker_net:
    enable_ipv6: true
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      config:
      - subnet: "172.20.0.0/16"
        gateway: "172.20.0.1"

services:

  twonav:
    image: tznb/twonav:latest
    container_name: "twonav"
    volumes:
      - '/data/docker_data/twonav/www:/www'
    restart: unless-stopped
    user: 0:0
    networks:
      docker_net:
        ipv4_address: "172.20.0.2"
        ipv6_address: "240e:35c:7fa:c900:1::2"
    ports:
      - 8202:80


  python_flask_docker:
    image: smnrao/python_flask_docker:latest
    container_name: "python_flask_docker"
    restart: always
    networks:
      docker_net:
        ipv4_address: "172.20.0.3"
    ports:
      - "8203:2222"
      - "8213:8780"
      - "8223:5000"
    volumes:
      - "/data/docker_data/python_flask_docker/app:/app"


  mi-gpt:
    image: idootop/mi-gpt:latest
    container_name: "mi-gpt"
    restart: always
    networks:
      docker_net:
        ipv4_address: "172.20.0.4"
    ports:
      - 8204:3000
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "/data/docker_data/mi-gpt/run.sh:/app/run.sh"
      - "/data/docker_data/mi-gpt/.migpt.js:/app/.migpt.js"
      - "/data/docker_data/mi-gpt/mi-gpt-tts-3.0.0:/app/mi-gpt-tts-3.0.0"
      - "/data/docker_data/mi-gpt/one-api:/app/one-api"
    env_file:
      - /data/docker_data/mi-gpt/.env
    command: sh -c "cd /app/ && sh /app/run.sh "


#  ventoy: 
#    image: thedrobe/iventoy-docker
#    container_name: "iventoy"
#    restart: on-failure:1
#    privileged: true
#    stop_signal: SIGINT
#    volumes:
#      - /data/docker_data/iventoy/iso:/app/iso
#      - /data/docker_data/iventoy/data:/app/data
#    network_mode: "host"




#  airprint:
#    image: anujdatar/cups
#    container_name: airprint
#    restart: always
#    networks:
#      docker_net:
#        ipv4_address: "172.20.0.5"
##        ipv6_address: "240e:35c:7fa:c900:1::5"
#    ports:
#      - 631:631
#    devices:
#      - /dev/bus/usb:/dev/bus/usb
#    environment:
#      - CUPSADMIN=smnra
#      - CUPSPASSWORD=smnra000
#      - TZ="America/Gotham"
#    volumes:
#      - /data/docker_data/airprint/cups:/etc/cups
#      - /data/docker_data/airprint/var/cache/cups:/var/cache/cups
#      - /data/docker_data/airprint/var/log/cups:/var/log/cups
#      - /data/docker_data/airprint/var/spool/cups:/var/spool/cups
#



#  guacd:
#    image: dushixiang/guacd:latest
#    user: 0:0
#    container_name: "next-terminal_guacd"
#    networks:
#      docker_net:
#        ipv4_address: "172.20.0.6"
##        ipv6_address: "240e:35c:7fa:c900:1::6"
#    volumes:
#      - /data/docker_data/next-terminal/data:/usr/local/next-terminal/data
#    restart: always
#
#  next-terminal:
#    image: dushixiang/next-terminal:latest
#    user: 0:0
#    container_name: "next-terminal"
#    environment:
#      DB: sqlite
#      GUACD_HOSTNAME: guacd
#      GUACD_PORT: 4822
#    networks:
#      docker_net:
#        ipv4_address: "172.20.0.7"
##        ipv6_address: "240e:35c:7fa:c900:1::7"
#    ports:
#      - "8207:8088"
#    volumes:
#      - /etc/localtime:/etc/localtime
#      - /data/docker_data/next-terminal/data:/usr/local/next-terminal/data
#    restart: always




